image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run:
  script:
    - pip install -r requirements.txt
    - LANG=en make
    - LANG=de make
    - LANG=es make
    - LANG=fr make
    - LANG=it make
    - LANG=tr make
    - mkdir -p public
    - cp -r output/en public/
  artifacts:
    paths:
      - public

pages:
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
